### ISSUE TITLE
TypeError: 'int' and 'str'

### ISSUE THREAD

**Issue by malware-kitten** [unixfreak0037/msoffice_decrypt#1]
```
Traceback (most recent call last):
  File "../gitlab/software/msoffice_decrypt/msoffice_decrypt.py", line 589, in <module>
    if decryptor.decrypt('VelvetSweatshop'):
  File "../gitlab/software/msoffice_decrypt/msoffice_decrypt.py", line 275, in decrypt
    key = self.get_encryption_key(password)
  File "../gitlab/software/msoffice_decrypt/msoffice_decrypt.py", line 290, in get_encryption_key
    return self.get_aes_128_encryption_key(password)
  File "../gitlab/software/msoffice_decrypt/msoffice_decrypt.py", line 394, in get_aes_128_encryption_key
    X1[index] = X1[index] ^ hash_final[index]
TypeError: unsupported operand type(s) for ^: 'int' and 'str'
```
Will send file that generates this bug.

**Comment by unixfreak0037** [comment]
Looks like we're not python2 compatible with this script.
